// Code generated by "stringer -type=TxType"; DO NOT EDIT.

package transactions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[txTypeUnknown-0]
	_ = x[TxTypeInternalTransfer-1]
	_ = x[TxTypeExternalTransfer-2]
	_ = x[txTypeSentinel-3]
}

const _TxType_name = "txTypeUnknownTxTypeInternalTransferTxTypeExternalTransfertxTypeSentinel"

var _TxType_index = [...]uint8{0, 13, 35, 57, 71}

func (i TxType) String() string {
	if i >= TxType(len(_TxType_index)-1) {
		return "TxType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TxType_name[_TxType_index[i]:_TxType_index[i+1]]
}
